{{- if .Values.podMonitoring.enabled }}
---
apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: {{ template "prometheus-postgres-exporter.fullname" $ }}-{{ .name }}
  namespace: {{ template "prometheus-postgres-exporter.namespace" $ }}
  labels:
    {{- include "prometheus-postgres-exporter.labels" $ | nindent 4 }}
    {{- if or $.Values.podMonitoring.defaults.labels .labels }}
    {{- toYaml (.labels | default $.Values.podMonitoring.defaults.labels) | nindent 4 }}
    {{- end }}
spec:
  endpoints:
  - port: http
    scheme: {{ $.Values.podMonitoring.scheme }}
    {{- if $.Values.podMonitoring.tlsConfig }}
    tls: {{ toYaml $.Values.podMonitoring.tlsConfig | nindent 6 }}
    {{- end }}
    path: {{ $.Values.podMonitoring.path }}
    interval: {{ .interval | default $.Values.podMonitoring.defaults.interval }}
    timeout: {{ .scrapeTimeout | default $.Values.podMonitoring.defaults.scrapeTimeout }}
  selector:
    matchLabels:
      {{- include "prometheus-postgres-exporter.selectorLabels" $ | nindent 6 }}
{{- end }}

